Update build-openwrt.yaml

diff --git a/.github/workflows/build-openwrt.yaml b/.github/workflows/build-openwrt.yaml
--- a/.github/workflows/build-openwrt.yaml
+++ b/.github/workflows/build-openwrt.yaml
@@ -17,7 +17,7 @@ env:
   CONFIG_FILE: mt6000.config
   GH_TOKEN: ${{ github.token }}
   DTS_FILE: mt7986a-glinet-gl-mt6000.dts
-
+  BRANCH: next-r4.6.14.rss.mtk   # ← opzionale: se lo lasci vuoto, lo calcola da solo
 jobs:
   check_commits:
     name: Check for new commits
@@ -31,16 +31,21 @@ jobs:
       - name: Check for new commits in pesa1234 repo
         id: check_commits
         run: |
-          remote_branch=$(git ls-remote https://github.com/${{ env.REMOTE_REPOSITORY }}.git "refs/heads/next-*" | sed -e 's|\(.*heads/\)||' | grep -vi 'test' | sort -V | tail -n1)
-          [ -n "$remote_branch" ] && latest_commit_sha=$(gh api "repos/${{ env.REMOTE_REPOSITORY }}/commits/${remote_branch}" --jq .sha)
-          [ -z "$latest_commit_sha" ] && { echo "*** COULD NOT GET latest_commit_sha FROM remote_branch=$remote_branch ***" ; exit 1; }
-          gh api "repos/${{ github.repository }}/releases/latest" --jq .body 2>/dev/null | grep -q "${latest_commit_sha}" && echo "new_commits=false" >> $GITHUB_OUTPUT || echo "new_commits=true" >> $GITHUB_OUTPUT
-          echo "remote_branch=${remote_branch}"
-          echo "release_prefix=${remote_branch%.rss*}"
-          echo "latest_commit_sha=$latest_commit_sha"
-          echo "remote_branch=${remote_branch}" >> $GITHUB_OUTPUT
-          echo "release_prefix=${remote_branch%.rss*}" >> $GITHUB_OUTPUT
-          echo "latest_commit_sha=$latest_commit_sha" >> $GITHUB_OUTPUT
+          if [ -z "${{ env.BRANCH }}" ]; then
+            remote_branch=$(git ls-remote https://github.com/${{ env.REMOTE_REPOSITORY }}.git "refs/heads/next-*" | sed -e 's|\(.*heads/\)||' | grep -vi 'test' | sort -V | tail -n1)
+            [ -n "$remote_branch" ] && latest_commit_sha=$(gh api "repos/${{ env.REMOTE_REPOSITORY }}/commits/${remote_branch}" --jq .sha)
+            [ -z "$latest_commit_sha" ] && { echo "*** COULD NOT GET latest_commit_sha FROM remote_branch=$remote_branch ***" ; exit 1; }
+            gh api "repos/${{ github.repository }}/releases/latest" --jq .body 2>/dev/null | grep -q "${latest_commit_sha}" && echo "new_commits=false" >> $GITHUB_OUTPUT || echo "new_commits=true" >> $GITHUB_OUTPUT
+            echo "remote_branch=${remote_branch}"
+            echo "release_prefix=${remote_branch%.rss*}"
+            echo "latest_commit_sha=$latest_commit_sha"
+            echo "remote_branch=${remote_branch}" >> $GITHUB_OUTPUT
+            echo "release_prefix=${remote_branch%.rss*}" >> $GITHUB_OUTPUT
+            echo "latest_commit_sha=$latest_commit_sha" >> $GITHUB_OUTPUT
+          else
+            remote_branch="${{ env.BRANCH }}"
+            echo "✅ Uso il branch specificato manualmente: $remote_branch"
+          fi
 
   build:
     name: Build OpenWrt
