allineati i file

diff --git a/.github/workflows/snapshot.yaml b/.github/workflows/snapshot.yaml
--- a/.github/workflows/snapshot.yaml
+++ b/.github/workflows/snapshot.yaml
@@ -162,7 +162,7 @@ jobs:
           # Scarica solo l'ultimo commit per risparmiare tempo e spazio
           fetch-depth: 1
 
-      # 2. Sincronizziamo i file verso 'snapshot' senza toccare il resto
+      # 2. Sincronizziamo i file verso '${{ env.BUILD_TYPE }}' senza toccare il resto
       - name: Sync Source to Cache Folder
         run: |
 
@@ -265,12 +265,7 @@ jobs:
           cd ${{ env.REPO_DIR }}
           make -j$(nproc) || make -j1 V=s
 
-      - name: Generate Index and Repo
-        run: |
-          cd ${{ env.REPO_DIR }}
-          make package/index
-
-      # 📦 prepara file release
+     # 📦 prepara file release
       - name: Prepare release
         run: |
           cd ${{ env.REPO_DIR }}
@@ -280,6 +275,7 @@ jobs:
           SHORT=${COMMIT:0:7}
           SOURCE_DIR=bin
           
+          # Creiamo le cartelle di destinazione pulite
           mkdir -p release/firmware
           mkdir -p release/packages
           
@@ -350,11 +346,13 @@ jobs:
           cd release
           tar -czf packages.tar.gz packages
           
+          # Esportiamo le variabili per gli step successivi
           echo "DATE=$DATE" >> $GITHUB_ENV
           echo "SHORT=$SHORT" >> $GITHUB_ENV
+          echo "✅ Preparazione completata con successo"
 
       - name: Publish Release
-        uses: softprops/action-gh-release@v2
+        uses: softprops/action-gh-release@v3.0.0
         with:
           tag_name: ${{ env.FINAL_TAG }}
           name: ${{ env.FINAL_TAG }}
@@ -362,8 +360,8 @@ jobs:
             ### OpenWrt Build Info
             - **Branch:** `${{ needs.check.outputs.branch }}`
             - **Commit SHA:** `${{ needs.check.outputs.commit }}`
-            - **Config Hash:** `${{ needs.check.outputs.config_hash }}`
-            - **Date:** ${{ env.DATE }}
+            - **${{ env.CONFIG_FILE }}:** `${{ needs.check.outputs.config_hash }}`
+            - **Date:** ${{ env.TS }}
             - **Type:** ${{ env.BUILD_TYPE }}
             ---
             📦 **Sito per i pacchetti:**
@@ -390,7 +388,7 @@ jobs:
 
           # 2. Copia dei file (Firmware e Pacchetti)
           find ${{ env.REPO_DIR }}/release/packages -type f -exec cp -v {} "$TARGET_PATH/" \;
-          find ${{ env.REPO_DIR }}/release/firmware -type f -exec cp -v {} "$TARGET_PATH/" \;
+          #find ${{ env.REPO_DIR }}/release/firmware -type f -exec cp -v {} "$TARGET_PATH/" \;
 
           # 3. Gestione Indice APK per il router
           INDEX_FILE=$(find ${{ env.REPO_DIR }}/bin -path "*/targets/*" -name "packages.adb" | head -n 1)
@@ -420,7 +418,7 @@ jobs:
           echo "<html><head><title>Build History</title></head><body style='font-family:sans-serif; padding:20px;'>" > "$MAIN_INDEX"
           echo "<h1>Cronologia Build ${{ env.BUILD_TYPE }}</h1><hr><ul>" >> "$MAIN_INDEX"
           
-          # Elenchiamo le cartelle dentro public/snapshot (dalla più recente)
+          # Elenchiamo le cartelle dentro public/${{ env.BUILD_TYPE }} (dalla più recente)
           # Usiamo basename per avere solo il nome della cartella nel link
           ls -dt "$BASE_DIR"/*/ 2>/dev/null | while read dirpath; do
             dirname=$(basename "$dirpath")
@@ -429,7 +427,7 @@ jobs:
           echo "</ul><p><a href='../'>.. Torna alla Home</a></p></body></html>" >> "$MAIN_INDEX"
 
       - name: Publish Pages
-        uses: peaceiris/actions-gh-pages@v4
+        uses: peaceiris/actions-gh-pages@v4.0.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./public
@@ -466,15 +464,15 @@ jobs:
           #gh api repos/${{ github.repository }}/releases \
           #  | jq -r '.[] | select(.tag_name | startswith("${{ env.BUILD_TYPE }}-")) | .tag_name' \
           #  | sed -E 's/.*-([0-9]{2}-[0-9]{2}-[0-9]{4}-[0-9]{4}).*/\1/' \
-          #  > /tmp/keep_snapshots.txt
+          #  > /tmp/keep_${{ env.BUILD_TYPE }}.txt
             
           gh api repos/erpomata/GL-MT6000/releases \
             | jq -r '.[] | select(.tag_name | startswith("${{ env.BUILD_TYPE }}-")) | .tag_name' \
             | sed -E 's/${{ env.BUILD_TYPE }}-([0-9]{2}-[0-9]{2}-[0-9]{4}-[0-9]{4}).*/${{ env.BUILD_TYPE }}\/\1/' \
-            > /tmp/keep_snapshots.txt
+            > /tmp/keep_${{ env.BUILD_TYPE }}.txt
    
           echo "✅ ${{ env.BUILD_TYPE }} da TENERE:"
-          cat /tmp/keep_snapshots.txt || true
+          cat /tmp/keep_${{ env.BUILD_TYPE }}.txt || true
    
           git fetch origin gh-pages
           git checkout gh-pages
@@ -482,14 +480,14 @@ jobs:
 
           for dir in ${{ env.BUILD_TYPE }}/*/ ; do
           
-            if [ ! -s /tmp/keep_snapshots.txt ]; then
-              echo "❌ keep_snapshots.txt vuoto → ABORT per sicurezza"
+            if [ ! -s /tmp/keep_${{ env.BUILD_TYPE }}.txt ]; then
+              echo "❌ keep_${{ env.BUILD_TYPE }}.txt vuoto → ABORT per sicurezza"
               exit 1
             fi
 
             snap="${dir%/}"
 
-            if grep -Fxq "$snap" /tmp/keep_snapshots.txt; then
+            if grep -Fxq "$snap" /tmp/keep_${{ env.BUILD_TYPE }}.txt; then
               echo "✅ Keeping $snap"
             else
               echo "🗑️ Removing $snap"
@@ -546,5 +544,5 @@ jobs:
           from: OpenWrt CI <${{ secrets.MAIL_USER }}>
 
       - name: Setup tmate session
-        uses: mxschmitt/action-tmate@v3
+        uses: mxschmitt/action-tmate@v3.23
         if: failure()
