corretta pulizia gh-pages

diff --git a/.github/workflows/snapshot.yaml b/.github/workflows/snapshot.yaml
--- a/.github/workflows/snapshot.yaml
+++ b/.github/workflows/snapshot.yaml
@@ -463,27 +463,40 @@ jobs:
           set -e
    
           echo "📦 Recupero release ancora presenti..."
-          gh api repos/${{ github.repository }}/releases \
+          #gh api repos/${{ github.repository }}/releases \
+          #  | jq -r '.[] | select(.tag_name | startswith("${{ env.BUILD_TYPE }}-")) | .tag_name' \
+          #  | sed -E 's/.*-([0-9]{2}-[0-9]{2}-[0-9]{4}-[0-9]{4}).*/\1/' \
+          #  > /tmp/keep_snapshots.txt
+            
+          gh api repos/erpomata/GL-MT6000/releases \
             | jq -r '.[] | select(.tag_name | startswith("${{ env.BUILD_TYPE }}-")) | .tag_name' \
-            | sed -E 's/.*-([0-9]{2}-[0-9]{2}-[0-9]{4}-[0-9]{4}).*/\1/' \
+            | sed -E 's/${{ env.BUILD_TYPE }}-([0-9]{2}-[0-9]{2}-[0-9]{4}-[0-9]{4}).*/${{ env.BUILD_TYPE }}\/\1/' \
             > /tmp/keep_snapshots.txt
    
-          echo "✅ Snapshot da TENERE:"
+          echo "✅ ${{ env.BUILD_TYPE }} da TENERE:"
           cat /tmp/keep_snapshots.txt || true
    
           git fetch origin gh-pages
           git checkout gh-pages
    
-          for dir in */ ; do
-            snap="${dir%/}"
-   
-            if grep -Fxq "$snap" /tmp/keep_snapshots.txt; then
-              echo "✅ Keeping gh-pages/$snap"
-            else
-              echo "🗑️  Removing gh-pages/$snap (release removed)"
-              rm -rf "$dir"
+
+          for dir in ${{ env.BUILD_TYPE }}/*/ ; do
+          
+            if [ ! -s /tmp/keep_snapshots.txt ]; then
+              echo "❌ keep_snapshots.txt vuoto → ABORT per sicurezza"
+              exit 1
             fi
-          done
+
+            snap="${dir%/}"
+
+            if grep -Fxq "$snap" /tmp/keep_snapshots.txt; then
+              echo "✅ Keeping $snap"
+            else
+              echo "🗑️ Removing $snap"
+              rm -rf "$snap"
+            fi
+        done
+
    
           if git status --porcelain | grep .; then
             git config user.name "github-actions[bot]"
