Update snapshot.yaml

diff --git a/.github/workflows/snapshot.yaml b/.github/workflows/snapshot.yaml
--- a/.github/workflows/snapshot.yaml
+++ b/.github/workflows/snapshot.yaml
@@ -118,20 +118,28 @@ jobs:
       # 2. Sincronizziamo i file verso 'snapshot' senza toccare il resto
       - name: Sync Source to Cache Folder
         run: |
-          # Crea la cartella snapshot se la cache era vuota
-          mkdir -p ${{ env.REPO_DIR }}
-          
-          # rsync è il modo più sicuro per "fondere" le cartelle:
-          # -a: mantiene i permessi e la struttura (archive)
-          # -v: mostra cosa sta facendo (verbose)
-          # --delete: NON lo usiamo, così non cancelliamo la cache (dl, staging_dir)
-          # --exclude='.git/': ignora la cartella Git dei sorgenti
+
           TEMP_NAME="temp_src${{ env.REPO_DIR }}"
-          #rsync -av --exclude='.git/' "$TEMP_NAME/" ${{ env.REPO_DIR }}/
-          rsync -aq "$TEMP_NAME/" ${{ env.REPO_DIR }}/
-          
-          # Eliminiamo la cartella temporanea
-          rm -rf "$TEMP_NAME/"
+          # Verifica che la sorgente esista prima di procedere
+          if [ -d "$TEMP_NAME" ]; then        
+            # Crea la cartella env.REPO_DIR se la cache era vuota
+            mkdir -p ${{ env.REPO_DIR }}
+            
+            # rsync è il modo più sicuro per "fondere" le cartelle:
+            # -a: mantiene i permessi e la struttura (archive)
+            # -v: mostra cosa sta facendo (verbose)
+            # --delete: NON lo usiamo, così non cancelliamo la cache (dl, staging_dir)
+            # --exclude='.git/': ignora la cartella Git dei sorgenti
+            
+            #rsync -av --exclude='.git/' "$TEMP_NAME/" ${{ env.REPO_DIR }}/
+            rsync -aq "$TEMP_NAME/" ${{ env.REPO_DIR }}/
+            
+            # Eliminiamo la cartella temporanea
+            rm -rf "$TEMP_NAME/"
+          else
+            echo "Errore: $TEMP_NAME non trovata! Checkout fallito?"
+            exit 1
+          fi
           
       - name: Update and Install feeds
         run: |
